name: build-mysql-docker

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.3
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3.3.1
        with:
          buildx-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image mysql
        run: |
          docker buildx build --push \
            --tag mariotani25/mysql:arm \
            --platform linux/arm/v7 -f Dockerfile .

      # - name: build the image mysql
      #   run: |
      #     docker buildx build --push \
      #       --tag mariotani25/mysql:latest \
      #       --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -f Dockerfile .
        
